site_name: Documentation
theme:
  name: material
  features:
    - toc.follow
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: 
      - 'Introduction': index.md
      - 'How to use this code': index_2.md
  - Physics Guide: 
      - 'Introduction': General_Physics/Overview.md   
  - Programmer Guide:
      - 'Introduction' : Programmer_Guide/Overview.md
      - 'Particle System':
        - 'What this section is about?' : Programmer_Guide/ParticleSystem/Overview.md 
        - 'Class: Particles' : Programmer_Guide/ParticleSystem/Class:Particles/Description.md 
        - 'Class: ParticleSystem' : Programmer_Guide/ParticleSystem/Class:ParticleSystem/Description.md 
      - 'Physics':
        - 'What this section is about?' : Programmer_Guide/Physics/Overview.md 
        - 'Class: Physics' : Programmer_Guide/Physics/Class:Physics/Description.md 
        - 'Class: Langevin_Dynamics' : Programmer_Guide/Physics/Class:LD/Description.md 
  - Some example system simulated:
      - 'What this section is about?' : Putting_together/Overview.md 
      - 'Open Interacting Gas': Putting_together/Interacting_gas.md
      - 'Confinement': Putting_together/Circular_boundary.md
      - 'Langevin_Dynamics': Putting_together/Langevin_Dynamics.md

                
 
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search
  - bibtex:
      bib_file: "ref.bib"

markdown_extensions:
  - toc:
        permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - tables 
  - md_in_html





copyright: |
  &copy; 2023 <a href="https://github.com/vishu-byte"  target="_blank" rel="noopener">Vishu Saini</a>       