site_name: Documentation
theme:
  name: material
  features:
    - toc.follow
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: 
      - 'Organization': index.md
  - Knowledge Base:
      - 'Particle System':
        - 'What this section is about?' : ParticleSystem/Overview.md 
        - 'Class: Particles' : ParticleSystem/Class:Particles/Description.md 
        - 'Class: ParticleSystem' : ParticleSystem/Class:ParticleSystem/Description.md 
      - 'Physics':
        - 'What this section is about?' : Physics/Overview.md 
        - 'Class: Langevin_Dynamics' : Physics/Class:LD/Description.md 
                
 
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML


markdown_extensions:
  - toc:
        permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  #- mdx_math  





copyright: |
  &copy; 2023 <a href="https://github.com/vishu-byte"  target="_blank" rel="noopener">Vishu Saini</a>       